## House Price Prediction using Linear Regression

Refer to this link for column description: https://www.kaggle.com/competitions/neolen-house-price-prediction/data

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

Read csv here. Change your file path.

In [3]:
file_path = "../data/house-price-prediction/data.csv"

df = pd.read_csv(file_path)

Print no. of rows & columns in the dataset

In [4]:
df.shape

(1259, 81)

View 5 row from the top

In [5]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

View 5 rows from the bottom/end

In [6]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1254,1255,60,RL,60.0,6931,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,165400
1255,1256,50,RM,52.0,6240,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,127500
1256,1257,20,RL,91.0,14303,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2008,WD,Normal,301500
1257,1258,30,RL,56.0,4060,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,99900
1258,1259,80,RL,59.0,9587,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,190000


Feature column are the predictor or independent variables. It is represented as X; or $x_1, x_2, .... x_n$

Target column are the response or dependent variables. They depend upon independent or predictor variables $x_1, x_2, .., x_n$. 

In $y = wx + b$, $y$ is the response/target/independent variable and $x$ is the feature/predictor/independent variable.

### Specify the feature and target columns here.

In [7]:
feature_column = ['LotArea', 'TotalBsmtSF', 'PoolArea']
target_column  = 'SalePrice'

In [8]:
print(f"Feature Columns: {feature_column}")
print(f"Target Column: {target_column}")

Feature Columns: ['LotArea', 'TotalBsmtSF', 'PoolArea']
Target Column: SalePrice

Show feature columns

In [9]:
df[feature_column]

      LotArea  TotalBsmtSF  PoolArea
0        8450          856         0
1        9600         1262         0
2       11250          920         0
3        9550          756         0
4       14260         1145         0
...       ...          ...       ...
1254     6931          746         0
1255     6240          884         0
1256    14303         1986         0
1257     4060          864         0
1258     9587          856         0

[1259 rows x 3 columns]

Show target column.

In [10]:
df[target_column]

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1254    165400
1255    127500
1256    301500
1257     99900
1258    190000
Name: SalePrice, Length: 1259, dtype: int64

### Split the dataset into train set and test set.

`train_test_split()` accepts `test_size` parameter that specify the test set proportion. `.2` means `20%` of the total data is split as test set.

`random_state` parameters helps to create re-producible train and test split. On each invocation of `train_test_split()` with `random_state=42` creates the same train and test split. See more here: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [11]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=.2, random_state=42)

In [12]:
print(f"Train Shape: {train.shape}")
print(f"Test Shape: {test.shape}")

Train Shape: (1007, 81)
Test Shape: (252, 81)

Separate out the feature and target column in train and test set.

In [13]:
train_x = train[feature_column]
train_y = train[target_column]

test_x = test[feature_column]
test_y = test[target_column]

In [14]:
## TODO : Write code here to to print train_x, train_y, test_x, test_y
## See how the columns are different in feature and target dataframes

Print shape of each dataframe here

In [15]:
train_x.shape, train_y.shape, test_x.shape, test_y.shape

((1007, 3), (1007,), (252, 3), (252,))

In [16]:
test_y

76      135750
1026    167500
43      130250
666     129000
529     200624
         ...
430      85400
32      179900
156     109500
376     148000
620      67000
Name: SalePrice, Length: 252, dtype: int64

## Linear Regression model 

Import LinearRegression model

In [17]:
from sklearn.linear_model import LinearRegression, SGDRegressor


# model = LinearRegression()
model = SGDRegressor(max_iter=1000, tol=1e-3, random_state=42)

Call `.fit()` method to learn the model parameters. 

In $y = wx + b$, `w` and `b` are the model parameters. `.fit()` computes these parameters.

In [18]:
model.fit(train_x, train_y)

SGDRegressor(random_state=42)

Print learned `w` here.

See how no. of values change on changing the no. of feature columns.

In [19]:
model.coef_

array([ 5.41799038e+12, -1.39194869e+13,  9.32059261e+12])

Print bias/intercept `b` here.

In [20]:
model.intercept_

array([-1.25670448e+11])

Use the learned linear regression model to predict on the test data set.

In [21]:
y_pred = model.predict(test_x)

In [22]:
print(y_pred)

[ 3.26659912e+16  3.27372754e+16  3.67889071e+16  8.57500007e+16
  1.48668628e+17  3.95635540e+16  3.61122822e+16  7.23816826e+16
  6.03036092e+16  3.80716218e+16  4.77875508e+16  5.62618916e+16
  1.63530381e+16  1.31146614e+16  4.81506455e+16  4.41375259e+16
  3.52063671e+16  5.12776921e+16  3.72510714e+16  2.87942778e+16
  2.51031283e+16  3.46862281e+16  3.23756751e+15  1.82887209e+16
  5.66371019e+16  1.22249368e+16  2.72207877e+16  7.16242573e+15
  5.91418625e+16  5.48840334e+16  3.42769702e+16  4.99376326e+16
  1.43214129e+16  5.81807086e+16  4.58993960e+16  3.42495663e+16
  4.01293356e+16  4.41151915e+15  3.96848836e+16  3.73287113e+16
  2.75746777e+16  2.89351078e+16  4.66719077e+16  4.57098676e+16
  3.63089033e+16  3.37853218e+16  1.98215851e+16  5.74127984e+16
  4.06521587e+16  2.61048049e+16 -2.51797038e+14  3.43634196e+16
  2.24498330e+16  4.31347725e+16  4.19432617e+16  2.15033079e+16
  4.15053164e+16  4.06424950e+16  3.08235248e+16  2.34435261e+17
  8.40919930e+15  1.83358557e+16  2.10115085e+16  4.52510849e+16
  3.27045033e+16  3.63001535e+16  2.27640526e+16  4.00270673e+16
  5.45023421e+16  4.64313365e+16  1.93979686e+16  5.12129962e+16
  1.08354854e+17  4.80622987e+16  2.86528458e+16  4.49149469e+16
  7.20769023e+16  3.83797518e+16  2.69906373e+16  6.16671228e+16
  2.64836152e+16  1.73034263e+17  5.40852424e+16  2.46314612e+16
  3.26421477e+16  2.69638712e+16  2.77137752e+16  2.60806395e+16
  3.80989621e+16  2.95624582e+16  3.88678816e+16  2.80425223e+16
  2.81766288e+16  4.51588241e+16  1.65338851e+15  4.57374682e+16
  5.30632012e+16  3.42885910e+16  2.90960362e+16  3.38983128e+16
  2.70383979e+16  3.21611327e+16  9.16629375e+16  2.70251123e+16
  2.91980542e+16  4.42582058e+16  5.73604782e+16  9.24025985e+15
  3.29734180e+16  5.50126287e+16  3.23025885e+16  3.39316910e+16
  3.43997482e+16  4.40506355e+16  2.78562164e+16  2.60691896e+16
  7.37378531e+16  1.70642989e+16  3.34979141e+16  2.94982152e+16
  4.52574506e+16  3.06006898e+16  4.01279627e+16  3.19355599e+16
  4.69280929e+16  7.73511948e+15  3.64280614e+16  4.30178416e+16
  1.96386569e+16  8.85973205e+16  6.16137893e+16  5.79607764e+16
  2.68159345e+16  3.03406204e+16  2.15253414e+16  2.71093047e+16
  2.01138943e+16  2.71912420e+16  3.68704889e+16  6.17190418e+16
  4.27909576e+16  3.76476715e+16  3.90069612e+16  4.14743423e+16
  3.63101491e+16  6.29943775e+16  3.56912822e+16  3.21140814e+16
  4.12290366e+16  4.09479131e+16  4.42197613e+16  1.43320721e+16
  3.01365169e+16  3.33067347e+16  4.61097857e+16  3.84311820e+16
  8.28556578e+14  3.79991454e+16  2.65618373e+16  4.84048043e+16
  5.36188819e+16  2.88213142e+16  4.77327251e+16  3.65008039e+16
  6.88191881e+16  9.98371065e+15  6.58246041e+15  2.86831445e+16
  2.22992776e+16  6.95609958e+16  4.04571111e+16 -2.51797038e+14
  4.56030655e+16  4.13922280e+16  1.99663589e+16  3.31039246e+16
  2.39742611e+16  2.15812061e+16  3.37624479e+16  2.58414433e+16
  3.27533804e+16  5.69333689e+16  4.03257561e+16  5.25367581e+16
  5.59243391e+16  3.47587839e+16  5.57438845e+16  1.16154352e+17
  9.74287799e+16  3.48997907e+16  3.31737127e+16  5.30823996e+16
  5.84496591e+16  4.06724121e+16  4.85642963e+16  2.99320042e+16
  4.41214210e+16  4.62051002e+16  3.91930464e+16 -6.91178769e+14
  1.66882601e+17  5.50967892e+16  5.26608970e+16  4.62911841e+16
  4.22494069e+16  6.08330248e+14  3.11972668e+16  2.31130510e+16
  3.34599643e+16  4.35979123e+16  3.75831285e+16  3.51386910e+16
  6.02635375e+16  5.95193238e+16  6.28556078e+16  3.81959633e+16
  5.58635790e+16  1.22249368e+16  3.24331686e+16  3.26375900e+16
  1.95430960e+16  3.70187972e+16  4.13839868e+16  5.42122780e+16
  4.48623366e+16  2.08531490e+16  7.57903257e+16  7.07276240e+16
  5.42149364e+16  3.35104140e+15  3.87259251e+16  6.32582359e+16
  3.60538465e+16  3.43366535e+16  3.09405510e+16  3.66003920e+16
  2.86928282e+16  3.49159553e+16  2.54481433e+16  3.35059824e+16
  3.32834654e+16  4.49082057e+16  5.82095450e+16  1.75218340e+16
  1.94764927e+16  4.46749659e+16  2.96535389e+16  2.37898599e+15
  4.26866032e+16  3.90094051e+16  3.58174636e+16  3.26610223e+16]

Import `root_mean_squared_error` from `sklearn.metrics` and calculate the RMSE for the predictions.

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.root_mean_squared_error.html

In [23]:
# write your code here
from sklearn.metrics import mean_squared_error, root_mean_squared_error


MSE = mean_squared_error(test_y, y_pred)
print(f"Mean Squared Error: {MSE}")

# calculate RMSE
# RMSE = 
print(f"Root Mean Squared Error: {RMSE}")

Mean Squared Error: 2.2572559116875734e+33

NameError: name 'RMSE' is not defined

Assignement: Add/remove features from `feature_column` and run all the code to see how `MSE` and `RMSE` changes. Document the RMSE and MSE and corresponding features.